export const eindAlgemeen = [
  { position: 1, points: 300 },
  { position: 2, points: 240 },
  { position: 3, points: 195 },
  { position: 4, points: 165 },
  { position: 5, points: 135 },
  { position: 6, points: 105 },
  { position: 7, points: 90 },
  { position: 8, points: 75 },
  { position: 9, points: 60 },
  { position: 10, points: 51 },
  { position: 11, points: 45 },
  { position: 12, points: 42 },
  { position: 13, points: 39 },
  { position: 14, points: 36 },
  { position: 15, points: 33 },
  { position: 16, points: 30 },
  { position: 17, points: 27 },
  { position: 18, points: 24 },
  { position: 19, points: 21 },
  { position: 20, points: 18 },
  { position: 21, points: 15 },
  { position: 22, points: 12 },
  { position: 23, points: 9 },
  { position: 24, points: 6 },
  { position: 25, points: 3 },
];

export const eindPunten = [
  { position: 1, points: 150 },
  { position: 2, points: 120 },
  { position: 3, points: 100 },
  { position: 4, points: 80 },
  { position: 5, points: 60 },
  { position: 6, points: 40 },
  { position: 7, points: 30 },
  { position: 8, points: 20 },
  { position: 9, points: 10 },
  { position: 10, points: 5 },
];

export const eindBerg = [
  { position: 1, points: 100 },
  { position: 2, points: 75 },
  { position: 3, points: 50 },
  { position: 4, points: 40 },
  { position: 5, points: 30 },
  { position: 6, points: 25 },
  { position: 7, points: 20 },
  { position: 8, points: 15 },
  { position: 9, points: 10 },
  { position: 10, points: 5 },
];

export const eindJongeren = [
  { position: 1, points: 80 },
  { position: 2, points: 60 },
  { position: 3, points: 40 },
  { position: 4, points: 30 },
  { position: 5, points: 25 },
  { position: 6, points: 20 },
  { position: 7, points: 15 },
  { position: 8, points: 10 },
  { position: 9, points: 5 },
  { position: 10, points: 2 },
];

export const etappe = [
  { position: 1, points: 100 },
  { position: 2, points: 80 },
  { position: 3, points: 65 },
  { position: 4, points: 55 },
  { position: 5, points: 45 },
  { position: 6, points: 35 },
  { position: 7, points: 30 },
  { position: 8, points: 25 },
  { position: 9, points: 20 },
  { position: 10, points: 17 },
  { position: 11, points: 15 },
  { position: 12, points: 14 },
  { position: 13, points: 13 },
  { position: 14, points: 12 },
  { position: 15, points: 11 },
  { position: 16, points: 10 },
  { position: 17, points: 9 },
  { position: 18, points: 8 },
  { position: 19, points: 7 },
  { position: 20, points: 6 },
  { position: 21, points: 5 },
  { position: 22, points: 4 },
  { position: 23, points: 3 },
  { position: 24, points: 2 },
  { position: 25, points: 1 },
];

export const truien = [
  {
    classification: 'Algemeen',
    extraPoints: 20,
  },
  {
    classification: 'Punten',
    jersey: 'groene trui',
    extraPoints: 10,
  },
  {
    classification: 'Berg',
    extraPoints: 10,
  },
  {
    classification: 'Jongeren',
    extraPoints: 5,
  },
];
